"""003_price_history

Revision ID: 19dc729a484f
Revises: 002fd410a290
Create Date: 2019-02-13 11:31:31.725080

"""
from alembic import op, context
from flask import current_app
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dc729a484f'
down_revision = '002fd410a290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('title_number', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('price_amount', sa.Integer(), nullable=False),
    sa.Column('price_currency', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['title_number'], ['title.title_number'], ),
    sa.PrimaryKeyConstraint('title_number', 'date')
    )
    # ### end Alembic commands ###

    context.execute("GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE \"price_history\" \
                    TO " + current_app.config.get('APP_SQL_USERNAME'))


def downgrade():
    context.execute("REVOKE SELECT, UPDATE, INSERT, DELETE ON TABLE \"price_history\" \
                    TO " + current_app.config.get('APP_SQL_USERNAME'))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    # ### end Alembic commands ###
